apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: service-accounts
  namespace: flux-system
spec:
  interval: 5m0s
  path: "./workload-identity/overlays/multi-namespace"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bookstore-frontend
  namespace: flux-system
spec:
  interval: 5m0s
  path: "./templates"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: service-accounts