apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-accounts.yaml

vars:
  - name: MANAGED_IDENTITY_CLIENT_ID
    objref:
      kind: ConfigMap
      name: flux-custom-values
      apiVersion: v1
    fieldref:
      fieldpath: data.managed_identity_client_id
  - name: KEY_VAULT_URL
    objref:
      kind: ConfigMap
      name: flux-custom-values
      apiVersion: v1
    fieldref:
      fieldpath: data.key_vault_url

configurations:
  - varreference.yaml