apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespaces.yaml
  - workload-identity-resources.yaml

configurations:
  - kustomizeconfig.yaml

vars:
  - name: MANAGED_IDENTITY_CLIENT_ID
    objref:
      kind: ConfigMap
      name: workload-identity-config
      apiVersion: v1
    fieldref:
      fieldpath: data.managed_identity_client_id

patches:
  - path: patch-service-account.yaml
    target:
      kind: ServiceAccount
      name: workload-identity-sa