apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-accounts.yaml
  - flux-custom-values-reference.yaml
  - flux-kustomizations.yaml

configurations:
  - varreference.yaml