apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-accounts.yaml

configMapGenerator:
  - name: workload-identity-vars
    behavior: merge
    envs:
      - flux-custom-values

vars:
  - name: managed_identity_client_id
    objref:
      kind: ConfigMap
      name: flux-custom-values
      apiVersion: v1
    fieldref:
      fieldpath: data.managed_identity_client_id
  - name: key_vault_url
    objref:
      kind: ConfigMap
      name: flux-custom-values
      apiVersion: v1
    fieldref:
      fieldpath: data.key_vault_url

configurations:
  - varreference.yaml