apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespaces.yaml
  - workload-identity-resources.yaml

vars:
  - name: managed_identity_client_id
    objref:
      kind: ConfigMap
      name: flux-config
      apiVersion: v1
    fieldref:
      fieldpath: data.managed_identity_client_id
  - name: key_vault_url
    objref:
      kind: Secret
      name: flux-secrets
      apiVersion: v1
    fieldref:
      fieldpath: data.key_vault_url

configurations:
  - kustomizeconfig.yaml