apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - workload-identity-resources.yaml

patchesStrategicMerge:
  - patch-service-account.yaml

vars:
  - name: managed_identity_client_id
    objref:
      kind: ConfigMap
      name: flux-custom-values
      apiVersion: v1
    fieldref:
      fieldpath: data.managed_identity_client_id
  - name: key_vault_url
    objref:
      kind: ConfigMap
      name: flux-custom-values
      apiVersion: v1
    fieldref:
      fieldpath: data.key_vault_url

configurations:
  - kustomizeconfig.yaml