apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-accounts.yaml
  - flux-custom-values-reference.yaml

configurations:
  - varreference.yaml

# Add ConfigMap references
configMapGenerator:
- name: key-vault-config
  namespace: default
  behavior: merge
  envs:
  - key-vault-config.env
- name: key-vault-config
  namespace: bookstore-frontend
  behavior: merge
  envs:
  - key-vault-config.env
- name: key-vault-config
  namespace: controller
  behavior: merge
  envs:
  - key-vault-config.env