apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: $(MANAGED_IDENTITY_CLIENT_ID)
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-sa
  namespace: bookstore-frontend
  annotations:
    azure.workload.identity/client-id: $(MANAGED_IDENTITY_CLIENT_ID)
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-sa
  namespace: controller
  annotations:
    azure.workload.identity/client-id: $(MANAGED_IDENTITY_CLIENT_ID)
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workload-identity-config
  namespace: default
data:
  managed_identity_client_id: $(MANAGED_IDENTITY_CLIENT_ID)
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workload-identity-config
  namespace: bookstore-frontend
data:
  managed_identity_client_id: $(MANAGED_IDENTITY_CLIENT_ID)
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workload-identity-config
  namespace: controller
data:
  managed_identity_client_id: $(MANAGED_IDENTITY_CLIENT_ID)