apiVersion: v1
kind: Service
metadata:
  name: controller-service
  namespace: controller
spec:
  selector:
    app: controller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8089
  type: ClusterIP