apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      serviceAccountName: workload-identity-sa
      containers:
      - name: controller
        image: andrewacr.azurecr.io/bookstore-controller:latest
        ports:
        - containerPort: 8089
        env:
        - name: SERVER_PORT
          value: "8089"
        - name: KEY_VAULT_URL
          valueFrom:
            configMapKeyRef:
              name: key-vault-config
              key: KEY_VAULT_URL
        - name: AZURE_EVENTHUB_NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: eventhub-config
              key: AZURE_EVENTHUB_NAMESPACE
        - name: AZURE_EVENTHUB_NAME
          valueFrom:
            configMapKeyRef:
              name: eventhub-config
              key: AZURE_EVENTHUB_NAME
        - name: AZURE_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: workload-identity-config
              key: managed_identity_client_id
        - name: AZURE_TENANT_ID
          valueFrom:
            configMapKeyRef:
              name: workload-identity-config
              key: azure_tenant_id
        - name: AZURE_FEDERATED_TOKEN_FILE
          value: /var/run/secrets/azure/tokens/azure-identity-token
        - name: AZURE_AUTHORITY_HOST
          value: https://login.microsoftonline.com/
        volumeMounts:
        - name: azure-identity-token
          mountPath: /var/run/secrets/azure/tokens
          readOnly: true
      volumes:
      - name: azure-identity-token
        projected:
          sources:
          - serviceAccountToken:
              path: azure-identity-token
              expirationSeconds: 3600
              audience: api://AzureADTokenExchange
