apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: workload-identity-sa
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./workload-identity/overlays/multi-namespace
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: workload-identity-config