apiVersion: v1
kind: Namespace
metadata:
  name: default
---
apiVersion: v1
kind: Namespace
metadata:
  name: bookstore-frontend
---
apiVersion: v1
kind: Namespace
metadata:
  name: controller
# Addiotnal namespaces wwill be added below