apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account-template.yaml

nameSuffix: -workload-identity

namespace: default

vars:
  - name: MANAGED_IDENTITY_CLIENT_ID
    objref:
      kind: ConfigMap
      name: workload-identity-config
      apiVersion: v1
    fieldref:
      fieldpath: data.managed_identity_client_id

configurations:
  - nameprefix-transformer.yaml
---
apiVersion: kustomize.config.k8s.io/v1
kind: NamePrefixTransformer
metadata:
  name: nameprefix-transformer
namePrefix: ""
nameSuffix: ""