apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-wi
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "${user_assigned_client_id}"
    keyvaultName: "${keyvault_name}"
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: secret1
          objectType: secret
          objectVersion: ""
    tenantId: "${tenant_id}"